services:
  db_test:
    image: postgres:15
    container_name: rural_producers_db_test
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: producers_db_test
